language: python
python:
    - "2.7"
script: python arrange.py
after_success:
    - export TO_PUSH=0
    - grep travis <(git log | head -n 6) || export TO_PUSH=1
    - git config --global user.email "travis@travis-ci.org"
    - git config --global user.name "Travis CI"
    - git add README.txt
    - git commit --message Travis-CI-build
    - git branch -D master
    - git checkout -b master
    - git remote remove origin
    - git remote add origin https://${GH_TOKEN}@github.com/Aaaaaaaah/windows-input-method-emoticon.git 
    - git branch -v
    - git remote -v
    - if [ ${TO_PUSH} -eq "1" ]; then git push --quiet --set-upstream; fi
